BUILD_TEST_TASK_TEMPLATE: &BUILD_TEST_TASK_TEMPLATE
  arch_check_script:
    - uname -am
  test_script:
      - composer install
      - composer run lint
      - composer run static-code-analysis
      - composer test

linux_arm64_task:  
  env:
    matrix:
      - IMAGE: php:8.2
      - IMAGE: php:8.1
      - IMAGE: php:8.0
  container:
    image: $IMAGE
    architecture: arm64
  pre_req_script: 
      - apt update --yes && apt install --yes zip unzip git
      - curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
      - php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - docker-php-ext-install sockets
  version_check_script: 
      - php --version
  << : *BUILD_TEST_TASK_TEMPLATE


macos_arm64_task:
# https://www.markhesketh.com/switching-multiple-php-versions-on-macos/
  env:
    matrix:
      - VERSION: 8.2
      - VERSION: 8.1
      - VERSION: 8.0
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  pre_req_script: 
      - brew install php@$VERSION composer
  version_check_script: 
      - php --version
  << : *BUILD_TEST_TASK_TEMPLATE


