name: Pact-PHP Compatibility Suite

on: [push, pull_request]

env:
  pact_do_not_track: true

jobs:
  v1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - uses: ramsey/composer-install@v2

      - name: Run Behat
        run: vendor/bin/behat compatibility-suite/pact-compatibility-suite/features/V1
  v2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - uses: ramsey/composer-install@v2

      - name: Run Behat
        run: vendor/bin/behat compatibility-suite/pact-compatibility-suite/features/V2
  v3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - uses: ramsey/composer-install@v2

      - name: Run Behat
        run: vendor/bin/behat compatibility-suite/pact-compatibility-suite/features/V3 --name '/^((?!Kafka|binary body \(negative|Message provider).)*$/'
